### ISSUE TITLE
refactor to a responsive theme

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-web#359]
I've actually got a branch in-flight on this, and it shouldn't be too terrible. This will handle #295 and make a lot of things less wonky. 

This particular issue will NOT change the overall look and feel of the site, but make things behave a lot better on smaller devices.

**Comment by mattstratton** [comment]
This issue can be the "meta-issue" for tracking smaller issues to get this implemented.

**Comment by bridgetkromhout** [comment]
Looking forward to this. Thanks.

**Comment by mattstratton** [comment]
We are almost there, folks! Please visit http://workstation.mattstratton.com and see if there are any issues that you think need fixing before we release it (that aren't already listed below).

Please note the following:
- Programs for events are likely NOT working properly yet (we haven't migrated them yet; we will do that when we release). You can look at http://workstation.mattstratton.com/events/2016-chicago/program/ to see a sample program in the responsive layout

Here are the outstanding issues:

- [ ] #441 Welcome page table columns run together
- [ ] #437 add some time of ux element to show upcoming events with dates in a list on the front page
- [ ] #436 twitter link in footer doesn't actually got to @devopsdays
- [ ] #421 create new events page
- [ ] #423 make a visual break between devopsdays slogan and page title on small viewports
- [ ] #259 decouple setting the browser title bar from setting the header text displayed in page

(note that #259 is debateable as to whether or not it is blocking in this release; @yvovandoorn really wants it though)

Please note that I'll tag this as a new version once we push this branch with these fixes.

**Comment by yvovandoorn** [comment]
I do really want it though.

On Tuesday, 31 May 2016, Matt Stratton <notifications@github.com> wrote:

> We are almost there, folks! Please visit
> http://workstation.mattstratton.com and see if there are any issues that
> you think need fixing before we release it (that aren't already listed
> below).
>
> Please note the following:
>
>    - Programs for events are likely NOT working properly yet (we haven't
>    migrated them yet; we will do that when we release). You can look at
>    http://workstation.mattstratton.com/events/2016-chicago/program/ to
>    see a sample program in the responsive layout
>
> Here are the outstanding issues:
>
>    - #441 <https://github.com/devopsdays/devopsdays-web/issues/441>
>    Welcome page table columns run together
>    - #437 <https://github.com/devopsdays/devopsdays-web/issues/437> add
>    some time of ux element to show upcoming events with dates in a list on the
>    front page
>    - #436 <https://github.com/devopsdays/devopsdays-web/issues/436>
>    twitter link in footer doesn't actually got to @devopsdays
>    <https://github.com/devopsdays>
>    - #421 <https://github.com/devopsdays/devopsdays-web/issues/421>
>    create new events page
>    - #423 <https://github.com/devopsdays/devopsdays-web/issues/423> make
>    a visual break between devopsdays slogan and page title on small viewports
>    - #259 <https://github.com/devopsdays/devopsdays-web/issues/259>
>    decouple setting the browser title bar from setting the header text
>    displayed in page
>
> (note that #259 <https://github.com/devopsdays/devopsdays-web/issues/259>
> is debateable as to whether or not it is blocking in this release;
> @yvovandoorn <https://github.com/yvovandoorn> really wants it though)
>
> Please note that I'll tag this as a new version once we push this branch
> with these fixes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/devopsdays/devopsdays-web/issues/359#issuecomment-222776443>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACkd_w3Mzncu0iNYKMvL8qt6T9rWKpXoks5qHHzpgaJpZM4Ie0Na>
> .
>


-- 

*Yvo van Doorn* — Manager, Technical Services (EMEA)

+31 6 38 74 07 46 <+316740746> – yvo@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/yvovandoorn/>  Twitter
<https://twitter.com/yvov>

CHEF

CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by bridgetkromhout** [comment]
> I do really want it though.

I don't see this feature that would admittedly be nice to have as a blocker for the release.

**Comment by bridgetkromhout** [comment]
Here's my edit of the "to do before merging" list as I see it:

<strike>- [ ] #441 Welcome page table columns run together</strike> **(not a release blocker)**

- [x] #437 add some time of ux element to show upcoming events with dates in a list <strike>on the front page</strike> **(doesn't need to be on the front page)**
- [x] #436 twitter link in footer doesn't actually got to @devopsdays
- [x] #421 create new events page

<strike>- [ ] #423 make a visual break between devopsdays slogan and page title on small viewports</strike> **(not a release blocker)**

<strike>- [ ] #259 decouple setting the browser title bar from setting the header text displayed in page</strike> **(not a release blocker)**
- [ ] **#485 - fix missing images for old talk detail pages**
- [ ] **#493 - fix drift in AMS schedule**
- [ ] **make sure to keep version of Silicon Valley program from the redesign branch**

**Comment by mattstratton** [comment]
Also updating the program.md files right?

**Comment by bridgetkromhout** [comment]
> Also updating the program.md files right?

I updated a bunch of them already. We can re-check them all in the responsive design to make sure they're okay; I'll add that.. I know I did upcoming ones that have no non-stock content, MSP, and SV. Not planning to change past ones.

**Comment by bridgetkromhout** [comment]
From my POV we just need https://github.com/devopsdays/devopsdays-web/issues/485 fixed and I think the responsive site is a good enough improvement on what we have that we should move on it, despite the several outstanding issues.

**Comment by mattstratton** [comment]
I agree. The rest of the stuff can be fixed in patches shortly.

**Comment by bridgetkromhout** [comment]
Added after discussion with @mattstratton:

- [ ] #421 - Redirect /presentations
- [ ] #513 - Fix unreadable AMS links

**Comment by bridgetkromhout** [comment]
One last fix - https://github.com/devopsdays/devopsdays-web/pull/520 band-aids my constant "where are the upcoming events".

**Comment by bridgetkromhout** [comment]
From my POV this meta-issue can be resolved at this point.

**Comment by yvovandoorn** [comment]
Works for me!

On Saturday, 4 June 2016, Bridget Kromhout <notifications@github.com> wrote:

> From my POV this meta-issue can be resolved at this point.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/devopsdays/devopsdays-web/issues/359#issuecomment-223776915>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACkd_6BafU8BGbwCUwGaPQW3B9C1Lx2Zks5qIeGmgaJpZM4Ie0Na>
> .
>


-- 

*Yvo van Doorn* — Manager, Technical Services (EMEA)

+31 6 38 74 07 46 <+316740746> – yvo@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/yvovandoorn/>  Twitter
<https://twitter.com/yvov>

CHEF

CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>
